import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";

import { PrimaryButton, SadieAssistant, SecondaryButton, SectionCard, VelvetScreen } from "@/components/holdoff-ui";
import { HOLD_OFF } from "@/constants/holdoff-theme";

function PlanCard({ name, price, detail, featured = false, disabled = false }: { name: string; price: string; detail: string; featured?: boolean; disabled?: boolean }) {
  const preview = () => Alert.alert("Preview mode", "Payments open at launch — you’re using the full preview.");
  return <SectionCard style={[styles.plan, featured && styles.featured, disabled && styles.disabled]}><View style={styles.planTop}><Text style={styles.planName}>{name}</Text>{featured ? <Text style={styles.badge}>MOST COMPLETE</Text> : null}</View><Text style={styles.price}>{price}</Text><Text style={styles.detail}>{detail}</Text>{disabled ? <View style={styles.coming}><Text style={styles.comingText}>Coming soon — available when licensed providers connect</Text></View> : featured ? <PrimaryButton label="See preview note" onPress={preview} /> : <SecondaryButton label="See preview note" onPress={preview} />}</SectionCard>;
}

export default function PricingScreen() {
  const router = useRouter();
  return <VelvetScreen><ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}><View style={styles.top}><Pressable onPress={() => router.back()} style={styles.back}><Text style={styles.backText}>‹</Text></Pressable><Text style={styles.eyebrow}>HOLD OFF PLANS</Text></View><Text style={styles.title}>Support that grows with your space.</Text><Text style={styles.subtitle}>Every plan respects the same boundary: HoldOff can support a pause, but only you decide what happens next.</Text><PlanCard name="Free" price="$0/mo" detail="Limited holds per day and basic Sadie support." /><PlanCard name="Pro" price="$24.99/mo" detail="Unlimited holds, full Sadie patterns, and connection insights." featured /><PlanCard name="One-Time" price="$199" detail="Lifetime Pro access, with no recurring charge." /><PlanCard name="Therapist Integration" price="$9.99/mo" detail="A future bridge for licensed providers and the people they support." disabled /><View style={styles.bottomNote}><Text style={styles.bottomText}>Payments open at launch — you’re using the full preview.</Text></View></ScrollView><SadieAssistant /></VelvetScreen>;
}

const styles = StyleSheet.create({
  scroll: { paddingTop: 28, paddingBottom: 112, gap: 12 }, top: { flexDirection: "row", alignItems: "center", gap: 12 }, back: { width: 44, height: 44, borderRadius: 22, borderWidth: 1, borderColor: HOLD_OFF.border, justifyContent: "center", alignItems: "center" }, backText: { color: HOLD_OFF.lavender, fontSize: 32, lineHeight: 35, fontWeight: "300", marginTop: -3 }, eyebrow: { color: HOLD_OFF.lavender, fontSize: 12, lineHeight: 17, letterSpacing: 1.1, fontWeight: "800" }, title: { color: HOLD_OFF.text, fontSize: 31, lineHeight: 38, fontWeight: "700", letterSpacing: -0.7, marginTop: 13 }, subtitle: { color: HOLD_OFF.muted, fontSize: 15, lineHeight: 23, marginBottom: 8 }, plan: { gap: 9 }, featured: { borderColor: "rgba(184,166,240,0.68)", backgroundColor: "#2B1B50" }, disabled: { opacity: 0.66 }, planTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, planName: { color: HOLD_OFF.text, fontSize: 18, lineHeight: 25, fontWeight: "700" }, badge: { color: HOLD_OFF.lavender, fontSize: 10, lineHeight: 14, fontWeight: "800", letterSpacing: 0.7 }, price: { color: HOLD_OFF.lavender, fontSize: 29, lineHeight: 36, fontWeight: "700" }, detail: { color: HOLD_OFF.muted, fontSize: 14, lineHeight: 21, marginBottom: 3 }, coming: { padding: 12, borderRadius: 13, borderWidth: 1, borderColor: HOLD_OFF.border, backgroundColor: "rgba(61,42,102,0.28)" }, comingText: { color: HOLD_OFF.muted, fontSize: 13, lineHeight: 19, textAlign: "center" }, bottomNote: { padding: 15, borderRadius: 16, borderWidth: 1, borderColor: "rgba(184,166,240,0.3)", backgroundColor: "rgba(184,166,240,0.1)", marginTop: 6 }, bottomText: { color: HOLD_OFF.lavender, fontSize: 13, lineHeight: 20, textAlign: "center", fontWeight: "700" },
});
